# ---------------------------------------------------------
# CE topology / scaling
# ---------------------------------------------------------

variable "ce_count" {
  description = "Number of single-node Secure Mesh v2 CE sites (1..3). Each originates the LB VIP via eBGP to the Azure Route Server for active/active ECMP."
  type        = number
  default     = 3

  validation {
    condition     = var.ce_count >= 1 && var.ce_count <= 3
    error_message = "ce_count must be between 1 and 3."
  }
}

# ---------------------------------------------------------
# Canada CE topology / scaling
# ---------------------------------------------------------

variable "ca_ce_count" {
  description = "Number of Canadian single-node Secure Mesh v2 CE sites (1..3)."
  type        = number
  default     = 3

  validation {
    condition     = var.ca_ce_count >= 1 && var.ca_ce_count <= 3
    error_message = "ca_ce_count must be between 1 and 3."
  }
}

variable "ca_site_prefix" {
  description = "Prefix for Canadian XC site names (site = <ca_site_prefix>-<ca_region_short>0<n>). Leave null to derive `<component>-ca`."
  type        = string
  default     = null
}

variable "region_short" {
  description = "Short region token used to build the per-CE key and site name (component `mcn-ce-ha` + region `eastus` -> site `mcn-ce-ha-eastus01`). Leave null (the default) to use var.location verbatim; set it only when the Azure region name is longer than you want inside object names."
  type        = string
  default     = null
}

variable "site_prefix" {
  description = "Prefix for XC site names (site = <prefix>-<region_short>0<n>). Leave null to use the released SMSv2 identity generation derived from var.component. Renaming a site replaces the CE VM, because the site name is the ClusterName baked into cloud-init and cloud-init only runs on first boot."
  type        = string
  default     = null
}

variable "smsv2_site_generation" {
  description = "Immutable identity generation appended to the default SMSv2 site prefix. The released default deliberately avoids the legacy mcn-ce-ha-* global-name reservations; do not decrement or reuse an earlier generation."
  type        = string
  default     = "smsv2"

  validation {
    condition     = can(regex("^[a-z0-9]([a-z0-9-]*[a-z0-9])?$", var.smsv2_site_generation))
    error_message = "smsv2_site_generation must be a DNS-style label: lowercase alphanumerics and hyphens, not starting or ending with a hyphen."
  }
}

variable "ce_asn" {
  description = "BGP ASN for the Customer Edge nodes (eBGP local ASN)."
  type        = number
  default     = 64512
}

variable "rs_asn" {
  description = "BGP ASN of the Azure Route Server (fixed by Azure at 65515)."
  type        = number
  default     = 65515
}

variable "enable_bgp" {
  description = "Enable the unsupported Azure Route Server BGP topology. Defaults false: the supported showcase uses Azure ILB instead. Setting true fails during planning, before Terraform, Azure, or F5 mutation, with the authoritative multihop-contract reason."
  type        = bool
  default     = false
}

variable "approve_registration" {
  description = "Approve each CE's runtime registration from Terraform (the xcsh_site_registration data source resolves the r-<uuid> registration name from the site name, and xcsh_registration_approval approves it). Two-phase by nature: the registration only exists after the CE has booted and registered, so the first apply plans no approval and a later apply creates it. Set false to leave approval to an operator."
  type        = bool
  default     = true
}

# ---------------------------------------------------------
# Site registration token (optional override)
# ---------------------------------------------------------
# The CE VM cloud-init consumes a tenant-scoped, reusable site registration
# token (ClusterName + Token). The token is now provider-generated by the
# xcsh_token.ce resource (its Computed uid) for Azure CE nodes; this var is an optional override.
variable "registration_token" {
  description = "Optional override for the Azure CE cloud-init site registration token. When empty (the default), enabled Azure CE nodes use the provider-generated xcsh_token.ce[0].uid; set a non-empty value to inject an externally-minted token instead."
  type        = string
  default     = ""
  sensitive   = true
}

variable "ce_os_version" {
  description = "CE OS version, set at create time. Empty deliberately selects the newest version advertised by F5 Distributed Cloud; the CE module now enforces an 80 GB disk default for the pinned Marketplace image. A concrete value is for reproducing an older build. Terraform cannot change this field afterwards: updates are rejected in every direction, including un-pinning. The platform can change it in place through the site upgrade_os action, but the provider cannot drive that action yet (xcsh#1390)."
  type        = string
  default     = ""
}

variable "ce_sw_version" {
  description = "CE F5 Distributed Cloud software version, set at create time. Empty deliberately selects the newest advertised build; the CE module now enforces an 80 GB disk default for the pinned Marketplace image. A concrete value is for reproducing an older build. The node always installs a destination build on first boot. Terraform cannot change this field afterwards, but the platform can change it in place through the site upgrade_sw action (xcsh#1390)."
  type        = string
  default     = ""
}
